prometheus:
  ingress:
    enabled: true
    ingressClassName: "gce"
    hosts:
      - prometheus.dev.altercabs.com
    paths:
      - /*
    annotations:
      kubernetes.io/ingress.class: "gce"
      kubernetes.io/ingress.allow-http: "true"

alertmanager:
  enabled: false

grafana:
  enabled: false # We are using the Central Grafana in Prod

prometheus:
  prometheusSpec:
    nodeSelector:
      cloud.google.com/gke-nodepool: development-cluster-node-pool

prometheus-node-exporter:
  nodeSelector: {}
  tolerations:
    - operator: Exists
