{{- if .Values.ingress.enabled -}}
apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: sonarqube-cert
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
spec:
  domains:
    {{- range .Values.ingress.hosts }}
    - {{ .name | quote }}
    {{- end }}
---
apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: sonarqube-frontend
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "sonarqube.labels" . | nindent 4 }}
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
{{- end }}
